apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name:  nginx
          image: nginx:latest
          ports:
            - containerPort: 80

